swagger: "2.0"

info:
  version: 1.0.0
  title: Game API
  description: A simple API to store some of my favorite video games

schemes:
  - http
  - https
host: localhost:8080
basePath: /

paths:
  /game:
    get:
      summary: A list of games.
      description: Returns a list containing all persons.
      parameters:
        - name: json
          in: query
          description: Should the data be displayed as json or not
          type: boolean
          required: false
      responses:
        200:
          description: A list of Person
          schema:
            type: array
            items:
              required:
                - username
              properties:
                description:
                  type: string
                name:
                  type: string
                date:
                  type: string 
                image:
                  type: string 
                developer:
                  type: string 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 